language: php

sudo: false

php:
- 5.6

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.4 WP_MULTISITE=0
#- WP_VERSION=4.3 WP_MULTISITE=0
#- WP_VERSION=4.2 WP_MULTISITE=0
#- WP_VERSION=4.1 WP_MULTISITE=0
#- WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit